// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.20.2
// source: networkfence.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// NetworkFenceRequest holds the required information to fence/unfence
// the cluster network.
type NetworkFenceRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Plugin specific parameters passed in as opaque key-value pairs.
	Parameters map[string]string `protobuf:"bytes,1,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Secrets required by the driver to complete the request.
	SecretName      string `protobuf:"bytes,2,opt,name=secret_name,json=secretName,proto3" json:"secret_name,omitempty"`
	SecretNamespace string `protobuf:"bytes,3,opt,name=secret_namespace,json=secretNamespace,proto3" json:"secret_namespace,omitempty"`
	// list of CIDR blocks on which the fencing/unfencing operation is expected
	// to be performed.
	Cidrs         []string `protobuf:"bytes,4,rep,name=cidrs,proto3" json:"cidrs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkFenceRequest) Reset() {
	*x = NetworkFenceRequest{}
	mi := &file_networkfence_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkFenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkFenceRequest) ProtoMessage() {}

func (x *NetworkFenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_networkfence_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkFenceRequest.ProtoReflect.Descriptor instead.
func (*NetworkFenceRequest) Descriptor() ([]byte, []int) {
	return file_networkfence_proto_rawDescGZIP(), []int{0}
}

func (x *NetworkFenceRequest) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *NetworkFenceRequest) GetSecretName() string {
	if x != nil {
		return x.SecretName
	}
	return ""
}

func (x *NetworkFenceRequest) GetSecretNamespace() string {
	if x != nil {
		return x.SecretNamespace
	}
	return ""
}

func (x *NetworkFenceRequest) GetCidrs() []string {
	if x != nil {
		return x.Cidrs
	}
	return nil
}

// NetworkFenceResponse is returned by the CSI-driver as a result of
// the FenceRequest call.
type NetworkFenceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkFenceResponse) Reset() {
	*x = NetworkFenceResponse{}
	mi := &file_networkfence_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkFenceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkFenceResponse) ProtoMessage() {}

func (x *NetworkFenceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_networkfence_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkFenceResponse.ProtoReflect.Descriptor instead.
func (*NetworkFenceResponse) Descriptor() ([]byte, []int) {
	return file_networkfence_proto_rawDescGZIP(), []int{1}
}

var File_networkfence_proto protoreflect.FileDescriptor

const file_networkfence_proto_rawDesc = "" +
	"\n" +
	"\x12networkfence.proto\x12\x05proto\"\x82\x02\n" +
	"\x13NetworkFenceRequest\x12J\n" +
	"\n" +
	"parameters\x18\x01 \x03(\v2*.proto.NetworkFenceRequest.ParametersEntryR\n" +
	"parameters\x12\x1f\n" +
	"\vsecret_name\x18\x02 \x01(\tR\n" +
	"secretName\x12)\n" +
	"\x10secret_namespace\x18\x03 \x01(\tR\x0fsecretNamespace\x12\x14\n" +
	"\x05cidrs\x18\x04 \x03(\tR\x05cidrs\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x16\n" +
	"\x14NetworkFenceResponse2\xb4\x01\n" +
	"\fNetworkFence\x12P\n" +
	"\x13FenceClusterNetwork\x12\x1a.proto.NetworkFenceRequest\x1a\x1b.proto.NetworkFenceResponse\"\x00\x12R\n" +
	"\x15UnFenceClusterNetwork\x12\x1a.proto.NetworkFenceRequest\x1a\x1b.proto.NetworkFenceResponse\"\x00B<Z:github.com/csi-addons/kubernetes-csi-addons/internal/protob\x06proto3"

var (
	file_networkfence_proto_rawDescOnce sync.Once
	file_networkfence_proto_rawDescData []byte
)

func file_networkfence_proto_rawDescGZIP() []byte {
	file_networkfence_proto_rawDescOnce.Do(func() {
		file_networkfence_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_networkfence_proto_rawDesc), len(file_networkfence_proto_rawDesc)))
	})
	return file_networkfence_proto_rawDescData
}

var file_networkfence_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_networkfence_proto_goTypes = []any{
	(*NetworkFenceRequest)(nil),  // 0: proto.NetworkFenceRequest
	(*NetworkFenceResponse)(nil), // 1: proto.NetworkFenceResponse
	nil,                          // 2: proto.NetworkFenceRequest.ParametersEntry
}
var file_networkfence_proto_depIdxs = []int32{
	2, // 0: proto.NetworkFenceRequest.parameters:type_name -> proto.NetworkFenceRequest.ParametersEntry
	0, // 1: proto.NetworkFence.FenceClusterNetwork:input_type -> proto.NetworkFenceRequest
	0, // 2: proto.NetworkFence.UnFenceClusterNetwork:input_type -> proto.NetworkFenceRequest
	1, // 3: proto.NetworkFence.FenceClusterNetwork:output_type -> proto.NetworkFenceResponse
	1, // 4: proto.NetworkFence.UnFenceClusterNetwork:output_type -> proto.NetworkFenceResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_networkfence_proto_init() }
func file_networkfence_proto_init() {
	if File_networkfence_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_networkfence_proto_rawDesc), len(file_networkfence_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_networkfence_proto_goTypes,
		DependencyIndexes: file_networkfence_proto_depIdxs,
		MessageInfos:      file_networkfence_proto_msgTypes,
	}.Build()
	File_networkfence_proto = out.File
	file_networkfence_proto_goTypes = nil
	file_networkfence_proto_depIdxs = nil
}
